# Generated by Django 4.2b1 on 2023-04-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_rename_product_productitem_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='code',
        ),
    ]
