# Generated by Django 4.2b1 on 2023-04-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_remove_productitem_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
