# Generated by Django 4.2b1 on 2023-04-17 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_rename_product_id_productitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Attribut',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit'},
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={'verbose_name': 'Déclinaison Produit'},
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.date.today, verbose_name='Date création'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prix unitaire HT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prix unitaire TTC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Offline'), (1, 'Online'), (2, 'Out of stock')], default=0),
        ),
        migrations.AddField(
            model_name='productitem',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='code_ean13',
            field=models.CharField(default=datetime.date.today, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='backoffice.product'),
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.productattribute', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Valeur attribut',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='productitem',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='product_item', to='backoffice.productattributevalue'),
        ),
    ]
