# Generated by Django 4.2b1 on 2023-04-17 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_productattribute_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date création'),
        ),
    ]
