# Generated by Django 4.2b1 on 2023-04-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_alter_product_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='code_ean13',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
