# Generated by Django 4.2b1 on 2023-04-17 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_alter_productitem_code_ean13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_creation',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date création'),
        ),
    ]
