# Generated by Django 4.2 on 2023-04-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_publication_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='code',
            field=models.CharField(blank=True, default='-', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productitem',
            name='code_ean13',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
