# Generated by Django 3.2.7 on 2021-10-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0002_auto_20211001_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geanalytiques',
            options={'managed': True, 'ordering': ['code'], 'verbose_name': 'CodeAnalytique'},
        ),
        migrations.RenameField(
            model_name='geanalytiques',
            old_name='nom',
            new_name='code',
        ),
    ]
