# Generated by Django 3.2.7 on 2021-10-16 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0003_auto_20211001_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stinventaires',
            name='qteConstat',
        ),
        migrations.AddField(
            model_name='geanalytiques',
            name='obsolete',
            field=models.BooleanField(default=False, help_text="code qui n'est plus utilisé, plus proposé", null=True),
        ),
        migrations.AddField(
            model_name='starticles',
            name='uniteStock',
            field=models.CharField(blank=True, default='', help_text="Nom de l'unité de décompte du stock et des sorties", max_length=8),
        ),
        migrations.AddField(
            model_name='starticles',
            name='uniteVente',
            field=models.CharField(blank=True, default='un', help_text="Nom de l'unité vente habituellement utilisée lors des achats", max_length=8),
        ),
        migrations.AddField(
            model_name='stinventaires',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='valeur des articles en stock du stock', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stmouvements',
            name='nbRations',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Lors des sorties: Nombre de rations par unité stock sortie', max_digits=10),
        ),
        migrations.AlterField(
            model_name='starticles',
            name='dernierAchat',
            field=models.DateField(help_text='Date de dernière entrée avec prix saisi', null=True),
        ),
        migrations.AlterField(
            model_name='starticles',
            name='qteParUniteVente',
            field=models.DecimalField(decimal_places=4, default=1, help_text="Nbre d'unité de stock proposé pour chaque unité de vente", max_digits=10),
        ),
        migrations.AlterField(
            model_name='starticles',
            name='rations',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Nombre de rations proposé pour chaque unité stock sortie', max_digits=10),
        ),
        migrations.AlterField(
            model_name='steffectifs',
            name='analytique',
            field=models.ForeignKey(default='00', help_text="PK Section analytique du camp à facturer '00' pour Cuisine", on_delete=django.db.models.deletion.RESTRICT, to='appli.geanalytiques'),
        ),
        migrations.AlterField(
            model_name='steffectifs',
            name='dateSaisie',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stinventaires',
            name='dateSaisie',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stinventaires',
            name='prixActuel',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Dernier prix d'achat, le jour de l'inventaire", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stinventaires',
            name='prixMoyen',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Prix unitaire historique du stock, FirstInFirstOut', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stmouvements',
            name='analytique',
            field=models.ForeignKey(help_text='Camp particulier à facturer, pas de valeur défaut', null=True, on_delete=django.db.models.deletion.RESTRICT, to='appli.geanalytiques'),
        ),
        migrations.AlterField(
            model_name='stmouvements',
            name='dateSaisie',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stmouvements',
            name='nbUnitesVente',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Lors des achats: Nombre stocké par unité vente', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stmouvements',
            name='prixUnit',
            field=models.DecimalField(decimal_places=4, help_text='PrixTTC saisi pour achats, Prix calculé pour autres mvts', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stmouvements',
            name='qteMouvement',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Quantité mouvementée signée en unité de stock', max_digits=10),
        ),
    ]
