from django.core.management.base import BaseCommand
import django.contrib.auth.get_user_model as get_user_model

from noegestion.models import GeAnalytique,StMagasin,StRayon,StFournisseur,StEffectif
from noegestion.models import StArticle,StMouvement,StInventaire

UserModel = get_user_model()

GeAnalytique_data = [
        {
            "abrege": "Tous camps",
            "axe": "ACTIVITES",
            "id": "00",
            "nom": "Tous camps",
            "obsolete": 0,
            "params": "-",
            "saisie": "2023-01-01"
        },
        {
            "abrege": "Pasto",
            "axe": "ACTIVITES",
            "id": "10",
            "nom": "Pasto indifférencié",
            "obsolete": 0,
            "params": "-",
            "saisie": "2023-01-01"
        },
        {
            "abrege": "Neige tous camps",
            "axe": "ACTIVITES",
            "id": "30",
            "nom": "Neige pour tous les camps",
            "obsolete": 0,
            "params": "-",
            "saisie": "2023-01-01"
        },
        {
            "abrege": "AVENTURE TT",
            "axe": "ACTIVITES",
            "id": "40",
            "nom": "AVENTURE TOUS CAMPS",
            "obsolete": 0,
            "params": "-",
            "saisie": "2023-01-01"
        },
        {
            "abrege": "Montagne tous",
            "axe": "ACTIVITES",
            "id": "50",
            "nom": "CAMPS MONTAGNE TOUS",
            "obsolete": 0,
            "params": "-",
            "saisie": "2023-01-01"
        },
        {
            "abrege": "Plongée Spéléo",
            "axe": "ACTIVITES",
            "id": "60",
            "nom": "60 PLONGEE ACTIVITES CLUB",
            "obsolete": 0,
            "params": "-",
            "saisie": "2023-01-01"
        },
        {
            "abrege": "Centres aerés",
            "axe": "ACTIVITES",
            "id": "70",
            "nom": "Tous Centres aérés",
            "obsolete": 0,
            "params": "-",
            "saisie": "2023-01-01"
        },
        {
            "abrege": "PASTO",
            "axe": "ACTIVITES",
            "id": "80",
            "nom": "PASTO",
            "obsolete": 0,
            "params": "-",
            "saisie": "2023-01-01"
        }
    ]
StMagasin_data =    [
        {
            "id": "FRI",
            "nom": "Frigo",
            "position": 2
        },
        {
            "id": "RES",
            "nom": "Réserve",
            "position": 1
        },
        {
            "id": "SUR",
            "nom": "Congélateur",
            "position": 3
        }
    ]
StRayon_data =      [
        {
            "id": "BSS",
            "nom": "Boissons",
            "position": 80
        },
        {
            "id": "CND",
            "nom": "Condiments",
            "position": 90
        },
        {
            "id": "FCL",
            "nom": "Féculents",
            "position": 10
        },
        {
            "id": "FRS",
            "nom": "Frais",
            "position": 20
        },
        {
            "id": "FRT",
            "nom": "Fruits",
            "position": 30
        },
        {
            "id": "LGM",
            "nom": "Légumes",
            "position": 40
        },
        {
            "id": "PSS",
            "nom": "Poisson",
            "position": 60
        },
        {
            "id": "SCR",
            "nom": "Sucré",
            "position": 70
        },
        {
            "id": "VND",
            "nom": "Viande",
            "position": 50
        }
    ]
StFournisseur_data = [
        {
            "id": 1,
            "nom": "LIDL"
        },
        {
            "id": 2,
            "nom": "METRO"
        },
        {
            "id": 3,
            "nom": "PASSION FROID"
        },
        {
            "id": 4,
            "nom": "RICHARD"
        },
        {
            "id": 5,
            "nom": "TRANSGOUMET"
        },
        {
            "id": 6,
            "nom": "TRANSGOURMET"
        }
    ]
StEffectif_data =   [
    {
        "id": 1,
        "jour": "2022-09-17",
        "midi_clients": 82,
        "midi_repas": 87,
        "ordi": "test",
        "prevu_clients": 81,
        "prevu_repas": 85,
        "saisie": "\"2024-12-07\"",
        "soir_clients": 92,
        "soir_repas": 98
    },
    {
        "id": 2,
        "jour": "2022-09-19",
        "midi_clients": 88,
        "midi_repas": 89,
        "ordi": "test",
        "prevu_clients": 85,
        "prevu_repas": 85,
        "saisie": "\"2024-12-07\"",
        "soir_clients": 95,
        "soir_repas": 99
    }
]
StArticle_data =    [
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 1,
            "magasin_id": "RES",
            "nom": "HUILE TOURNESOL  X 1L",
            "nom_court": "HUILE TO/X 1L",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 4.588,
            "prix_moyen": 4.1078,
            "qte_mini": 15,
            "qte_stock": 11,
            "rations": 20,
            "rayon_id": "CND",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-08-21",
            "fournisseur_id": 6,
            "id": 2,
            "magasin_id": "RES",
            "nom": "JUS ORANGE/POMME PtDej",
            "nom_court": "JUS ORAN/tDej",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 1.18,
            "prix_moyen": 1.702,
            "qte_mini": 0,
            "qte_stock": 130,
            "rations": 8,
            "rayon_id": "BSS",
            "saisie": "2022-08-21",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-17",
            "fournisseur_id": 4,
            "id": 3,
            "magasin_id": "FRI",
            "nom": "KIWIS FRAIS PIECE",
            "nom_court": "KIWIS FR/unit",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 0.49,
            "prix_moyen": 0.49,
            "qte_mini": 0,
            "qte_stock": 0,
            "rations": 1,
            "rayon_id": "FRT",
            "saisie": "2024-12-05",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-10-07",
            "fournisseur_id": 6,
            "id": 4,
            "magasin_id": "RES",
            "nom": "LAIT COCO BTE 1L",
            "nom_court": "LAIT COC/E 1L",
            "obsolete": 0,
            "ordi": "Matth2-PC",
            "prix_actuel": 4.19,
            "prix_moyen": 4.19,
            "qte_mini": 1,
            "qte_stock": 0,
            "rations": 12,
            "rayon_id": "FRS",
            "saisie": "2022-10-07",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-21",
            "fournisseur_id": 6,
            "id": 5,
            "magasin_id": "RES",
            "nom": "LAIT UHT 1L",
            "nom_court": "LAIT UHT/T 1L",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 4.4099,
            "prix_moyen": 4.4099,
            "qte_mini": 60,
            "qte_stock": 0,
            "rations": 10,
            "rayon_id": "FRS",
            "saisie": "2022-09-21",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-08-22",
            "fournisseur_id": 6,
            "id": 6,
            "magasin_id": "FRI",
            "nom": "LARDONS FUMES    KG",
            "nom_court": "LARDONS /  KG",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 6.0483,
            "prix_moyen": 6.0483,
            "qte_mini": 5,
            "qte_stock": 10,
            "rations": 0,
            "rayon_id": "VND",
            "saisie": "2022-08-22",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-08-22",
            "fournisseur_id": 6,
            "id": 7,
            "magasin_id": "RES",
            "nom": "MAIS DOUX        3/1",
            "nom_court": "MAIS DOU/ 3/1",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 5.7761,
            "prix_moyen": 5.7761,
            "qte_mini": 6,
            "qte_stock": 19,
            "rations": 30,
            "rayon_id": "LGM",
            "saisie": "2022-08-22",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-10-07",
            "fournisseur_id": 1,
            "id": 8,
            "magasin_id": "RES",
            "nom": "MUESLI CROUST",
            "nom_court": "MUESLI C/OUST",
            "obsolete": 0,
            "ordi": "Matth2-PC",
            "prix_actuel": 2.47,
            "prix_moyen": 2.47,
            "qte_mini": 1,
            "qte_stock": 0,
            "rations": 10,
            "rayon_id": "SCR",
            "saisie": "2022-10-07",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-17",
            "fournisseur_id": 4,
            "id": 9,
            "magasin_id": "FRI",
            "nom": "NECTARINES KG",
            "nom_court": "NECTARIN/S KG",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 2.99,
            "prix_moyen": 2.99,
            "qte_mini": 10,
            "qte_stock": 0,
            "rations": 5,
            "rayon_id": "FRT",
            "saisie": "2022-09-17",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 10,
            "magasin_id": "SUR",
            "nom": "OIGNON EMINCE GEL KG",
            "nom_court": "OIGNON E/L KG",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 1.2396,
            "prix_moyen": 1.2396,
            "qte_mini": 5,
            "qte_stock": 5,
            "rations": 0,
            "rayon_id": "LGM",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-17",
            "fournisseur_id": 4,
            "id": 11,
            "magasin_id": "RES",
            "nom": "OIGNONS FRAIS",
            "nom_court": "OIGNONS /RAIS",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 1.29,
            "prix_moyen": 1.29,
            "qte_mini": 0,
            "qte_stock": 0,
            "rations": 0,
            "rayon_id": "LGM",
            "saisie": "2022-09-17",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-08-18",
            "fournisseur_id": 6,
            "id": 12,
            "magasin_id": "RES",
            "nom": "OLIVES NOIRES 4/4",
            "nom_court": "OLIVES N/ 4/4",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 1.7175,
            "prix_moyen": 1.7175,
            "qte_mini": 6,
            "qte_stock": 1,
            "rations": 0,
            "rayon_id": "CND",
            "saisie": "2022-08-18",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2023-02-07",
            "fournisseur_id": 4,
            "id": 13,
            "magasin_id": "FRI",
            "nom": "ORANGES FRAICHES  KG",
            "nom_court": "ORANGES /  KG",
            "obsolete": 0,
            "ordi": "MATTH8",
            "prix_actuel": 1.055,
            "prix_moyen": 1.055,
            "qte_mini": 5,
            "qte_stock": 0,
            "rations": 5,
            "rayon_id": "FRT",
            "saisie": "2023-02-07",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 14,
            "magasin_id": "RES",
            "nom": "PATES COQUILLETTE KG",
            "nom_court": "PATES CO/E KG",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 1.304,
            "prix_moyen": 1.304,
            "qte_mini": 5,
            "qte_stock": 5,
            "rations": 15,
            "rayon_id": "FCL",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-08-12",
            "fournisseur_id": 6,
            "id": 15,
            "magasin_id": "RES",
            "nom": "PATES FARFALLES KG",
            "nom_court": "PATES FA/S KG",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 1.3757,
            "prix_moyen": 1.3757,
            "qte_mini": 5,
            "qte_stock": 5,
            "rations": 13,
            "rayon_id": "FCL",
            "saisie": "2022-08-12",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 5,
            "id": 16,
            "magasin_id": "SUR",
            "nom": "PAUPIETTE VEAU GEL",
            "nom_court": "PAUPIETT/ GEL",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 14.5906,
            "prix_moyen": 14.5906,
            "qte_mini": 0,
            "qte_stock": 0,
            "rations": 0,
            "rayon_id": "VND",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-23",
            "fournisseur_id": 4,
            "id": 17,
            "magasin_id": "FRI",
            "nom": "RAISIN FRAIS KG",
            "nom_court": "RAISIN F/S KG",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 2.99,
            "prix_moyen": 2.99,
            "qte_mini": 0,
            "qte_stock": 3,
            "rations": 5,
            "rayon_id": "FRT",
            "saisie": "2022-09-23",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 18,
            "magasin_id": "SUR",
            "nom": "RAVIOLIS FROMAGE SURG",
            "nom_court": "RAVIOLIS/SURG",
            "obsolete": 0,
            "ordi": "Matth2-PC",
            "prix_actuel": 12.2696,
            "prix_moyen": 12.2696,
            "qte_mini": 0,
            "qte_stock": 0,
            "rations": 7,
            "rayon_id": "FCL",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-08-22",
            "fournisseur_id": 6,
            "id": 19,
            "magasin_id": "RES",
            "nom": "RIZ LONG GR US KG",
            "nom_court": "RIZ LONG/S KG",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 1.1151,
            "prix_moyen": 1.1151,
            "qte_mini": 5,
            "qte_stock": 8,
            "rations": 16,
            "rayon_id": "FCL",
            "saisie": "2022-08-22",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-08-23",
            "fournisseur_id": 4,
            "id": 20,
            "magasin_id": "FRI",
            "nom": "SALADES DIVERSES",
            "nom_court": "SALADES /RSES",
            "obsolete": 0,
            "ordi": "MATTH8",
            "prix_actuel": 1.3609,
            "prix_moyen": 1.3609,
            "qte_mini": 12,
            "qte_stock": 0,
            "rations": 10,
            "rayon_id": "LGM",
            "saisie": "2022-08-23",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 21,
            "magasin_id": "SUR",
            "nom": "SUNDAE BTE CONG",
            "nom_court": "SUNDAE B/CONG",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 0.7242,
            "prix_moyen": 0.7242,
            "qte_mini": 40,
            "qte_stock": 37,
            "rations": 1,
            "rayon_id": "SCR",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 22,
            "magasin_id": "SUR",
            "nom": "TARTES CITRON POUR 10",
            "nom_court": "TARTES C/R 10",
            "obsolete": 0,
            "ordi": "HP-JB-RYZEN5000",
            "prix_actuel": 3.4751,
            "prix_moyen": 5.385,
            "qte_mini": 1,
            "qte_stock": 6,
            "rations": 10,
            "rayon_id": "SCR",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 23,
            "magasin_id": "SUR",
            "nom": "TARTES MYRTILLES POUR 10",
            "nom_court": "TARTES M/R 10",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 8.3482,
            "prix_moyen": 8.3482,
            "qte_mini": 1,
            "qte_stock": 3,
            "rations": 10,
            "rayon_id": "SCR",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-14",
            "fournisseur_id": 6,
            "id": 24,
            "magasin_id": "RES",
            "nom": "THE DIVERS 100SCH",
            "nom_court": "THE DIVE/0SCH",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 4.76,
            "prix_moyen": 4.76,
            "qte_mini": 1,
            "qte_stock": 1,
            "rations": 100,
            "rayon_id": "SCR",
            "saisie": "2022-09-14",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-23",
            "fournisseur_id": 4,
            "id": 25,
            "magasin_id": "FRI",
            "nom": "TOMATES FRAICHES",
            "nom_court": "TOMATES /CHES",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 2.39,
            "prix_moyen": 2.39,
            "qte_mini": 20,
            "qte_stock": 0,
            "rations": 5,
            "rayon_id": "LGM",
            "saisie": "2022-09-23",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-08-22",
            "fournisseur_id": 6,
            "id": 26,
            "magasin_id": "RES",
            "nom": "TOMATES PEL/CONC 5/1",
            "nom_court": "TOMATES / 5/1",
            "obsolete": 0,
            "ordi": "Matth2-PC",
            "prix_actuel": 5.5566,
            "prix_moyen": 5.5566,
            "qte_mini": 3,
            "qte_stock": 1,
            "rations": 50,
            "rayon_id": "LGM",
            "saisie": "2022-08-22",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 5,
            "id": 27,
            "magasin_id": "SUR",
            "nom": "AIGUI POULET GEL",
            "nom_court": "AIGUI PO/ GEL",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 8.48,
            "prix_moyen": 8.48,
            "qte_mini": 0,
            "qte_stock": 8,
            "rations": 0,
            "rayon_id": "VND",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 28,
            "magasin_id": "RES",
            "nom": "ANANAS MORC BTE 3/1",
            "nom_court": "ANANAS M/ 3/1",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 6.908,
            "prix_moyen": 7.0979,
            "qte_mini": 3,
            "qte_stock": 6,
            "rations": 25,
            "rayon_id": "FRT",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-17",
            "fournisseur_id": 4,
            "id": 29,
            "magasin_id": "RES",
            "nom": "BANANES KG",
            "nom_court": "BANANES /S KG",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 1.89,
            "prix_moyen": 1.89,
            "qte_mini": 5,
            "qte_stock": 0,
            "rations": 5,
            "rayon_id": "FRT",
            "saisie": "2022-09-17",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 3,
            "id": 30,
            "magasin_id": "SUR",
            "nom": "BARRES GLACEE UNITE",
            "nom_court": "BARRES G/NITE",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 0.844,
            "prix_moyen": 0.844,
            "qte_mini": 48,
            "qte_stock": 205,
            "rations": 1,
            "rayon_id": "SCR",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 31,
            "magasin_id": "FRI",
            "nom": "BEURRE MICRO X 100",
            "nom_court": "BEURRE M/ 100",
            "obsolete": 0,
            "ordi": "HP-JB-RYZEN5000",
            "prix_actuel": 0.0956,
            "prix_moyen": 0.0894,
            "qte_mini": 100,
            "qte_stock": 0,
            "rations": 1,
            "rayon_id": "FRS",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 32,
            "magasin_id": "FRI",
            "nom": "BEURRE PLQ 250G PIEC",
            "nom_court": "BEURRE P/PIEC",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 3.9325,
            "prix_moyen": 3.9325,
            "qte_mini": 4,
            "qte_stock": 0,
            "rations": 20,
            "rayon_id": "FRS",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-08-21",
            "fournisseur_id": 1,
            "id": 33,
            "magasin_id": "RES",
            "nom": "BISCUIT BN PAQ DE 15",
            "nom_court": "BISCUIT /E 15",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 2.3,
            "prix_moyen": 2.3,
            "qte_mini": 0,
            "qte_stock": 0,
            "rations": 0,
            "rayon_id": "SCR",
            "saisie": "2022-08-21",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 34,
            "magasin_id": "RES",
            "nom": "BISCUITS PORTIONS",
            "nom_court": "BISCUITS/IONS",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 0.196,
            "prix_moyen": 0.1923,
            "qte_mini": 0,
            "qte_stock": 310,
            "rations": 1,
            "rayon_id": "SCR",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 5,
            "id": 35,
            "magasin_id": "RES",
            "nom": "BOUIL VEAU LIE",
            "nom_court": "BOUIL VE/ LIE",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 16.421,
            "prix_moyen": 16.421,
            "qte_mini": 0,
            "qte_stock": 0,
            "rations": 0,
            "rayon_id": "CND",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-09",
            "fournisseur_id": 1,
            "id": 36,
            "magasin_id": "RES",
            "nom": "BRIOCHE TRANCHEE",
            "nom_court": "BRIOCHE /CHEE",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 2.32,
            "prix_moyen": 2.32,
            "qte_mini": 1,
            "qte_stock": 4,
            "rations": 10,
            "rayon_id": "SCR",
            "saisie": "2022-09-09",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-10-07",
            "fournisseur_id": 1,
            "id": 37,
            "magasin_id": "RES",
            "nom": "BRIOCHETTES 130g",
            "nom_court": "BRIOCHET/130g",
            "obsolete": 0,
            "ordi": "Matth2-PC",
            "prix_actuel": 0.16,
            "prix_moyen": 0.16,
            "qte_mini": 5,
            "qte_stock": 12,
            "rations": 1,
            "rayon_id": "SCR",
            "saisie": "2022-10-07",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-13",
            "fournisseur_id": 1,
            "id": 38,
            "magasin_id": "RES",
            "nom": "BROWNIES INDIVIDUEL",
            "nom_court": "BROWNIES/DUEL",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 0.1866,
            "prix_moyen": 0.1866,
            "qte_mini": 60,
            "qte_stock": 0,
            "rations": 1,
            "rayon_id": "SCR",
            "saisie": "2022-09-13",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 39,
            "magasin_id": "RES",
            "nom": "CAFE ARABICA KG",
            "nom_court": "CAFE ARA/A KG",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 7.671,
            "prix_moyen": 7.671,
            "qte_mini": 6,
            "qte_stock": 1,
            "rations": 840,
            "rayon_id": "SCR",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-14",
            "fournisseur_id": 1,
            "id": 40,
            "magasin_id": "RES",
            "nom": "CEREALES DU MATIN",
            "nom_court": "CEREALES/ATIN",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 2.09,
            "prix_moyen": 2.167,
            "qte_mini": 5,
            "qte_stock": 3,
            "rations": 20,
            "rayon_id": "FCL",
            "saisie": "2022-09-14",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 41,
            "magasin_id": "FRI",
            "nom": "CHANTILLY BOMBE 1L",
            "nom_court": "CHANTILL/E 1L",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 7.3037,
            "prix_moyen": 7.2182,
            "qte_mini": 0,
            "qte_stock": 10,
            "rations": 15,
            "rayon_id": "SCR",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-06-08",
            "fournisseur_id": 5,
            "id": 42,
            "magasin_id": "RES",
            "nom": "CHOCOLAT POUDRE DOSETTES",
            "nom_court": "CHOCOLAT/TTES",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 0.15,
            "prix_moyen": 0.15,
            "qte_mini": 0,
            "qte_stock": 100,
            "rations": 0,
            "rayon_id": "SCR",
            "saisie": "2022-06-08",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 43,
            "magasin_id": "RES",
            "nom": "CONFITURE INDIV BARQ UNITE",
            "nom_court": "CONFITUR/NITE",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 0.0679,
            "prix_moyen": 0.0679,
            "qte_mini": 120,
            "qte_stock": 0,
            "rations": 1,
            "rayon_id": "SCR",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-14",
            "fournisseur_id": 2,
            "id": 44,
            "magasin_id": "RES",
            "nom": "CONFITURE POT 320G UNIT",
            "nom_court": "CONFITUR/UNIT",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 4.9,
            "prix_moyen": 4.9,
            "qte_mini": 0,
            "qte_stock": 7,
            "rations": 0,
            "rayon_id": "SCR",
            "saisie": "2022-09-14",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 45,
            "magasin_id": "SUR",
            "nom": "COTES DE PORC GEL KG",
            "nom_court": "COTES DE/L KG",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 4.4521,
            "prix_moyen": 4.4521,
            "qte_mini": 20,
            "qte_stock": 3,
            "rations": 7,
            "rayon_id": "VND",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-08-04",
            "fournisseur_id": 5,
            "id": 46,
            "magasin_id": "FRI",
            "nom": "CREME ANGLAISE",
            "nom_court": "CREME AN/AISE",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 3.1966,
            "prix_moyen": 3.1966,
            "qte_mini": 0,
            "qte_stock": 0,
            "rations": 0,
            "rayon_id": "SCR",
            "saisie": "2022-08-04",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-16",
            "fournisseur_id": 6,
            "id": 47,
            "magasin_id": "FRI",
            "nom": "CREME FR LIQU L/C 1L",
            "nom_court": "CREME FR/C 1L",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 3.1544,
            "prix_moyen": 3.2008,
            "qte_mini": 6,
            "qte_stock": 7,
            "rations": 8,
            "rayon_id": "FRS",
            "saisie": "2022-09-16",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 48,
            "magasin_id": "SUR",
            "nom": "CROISSANTS GEL UNITE",
            "nom_court": "CROISSAN/NITE",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 0.2278,
            "prix_moyen": 0.2278,
            "qte_mini": 0,
            "qte_stock": 0,
            "rations": 1,
            "rayon_id": "SCR",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-08-08",
            "fournisseur_id": 3,
            "id": 49,
            "magasin_id": "SUR",
            "nom": "CUB COLIN ALK CEREAL",
            "nom_court": "CUB COLI/REAL",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 8.6615,
            "prix_moyen": 8.6615,
            "qte_mini": 0,
            "qte_stock": 0,
            "rations": 0,
            "rayon_id": "PSS",
            "saisie": "2022-08-08",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 50,
            "magasin_id": "FRI",
            "nom": "FROM BRESSE BLEU 500GRS",
            "nom_court": "FROM BRE/0GRS",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 7.1107,
            "prix_moyen": 7.1107,
            "qte_mini": 0,
            "qte_stock": 0,
            "rations": 10,
            "rayon_id": "FRS",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 51,
            "magasin_id": "FRI",
            "nom": "FROM CAMEMBERT 250GRS",
            "nom_court": "FROM CAM/0GRS",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 2.3674,
            "prix_moyen": 2.3674,
            "qte_mini": 1,
            "qte_stock": 0,
            "rations": 4,
            "rayon_id": "FRS",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 52,
            "magasin_id": "FRI",
            "nom": "FROM COMTE BLOC X 500 GRS",
            "nom_court": "FROM COM/ GRS",
            "obsolete": 0,
            "ordi": "HP-JB-RYZEN5000",
            "prix_actuel": 11.9373,
            "prix_moyen": 11.9373,
            "qte_mini": 1,
            "qte_stock": 0,
            "rations": 8,
            "rayon_id": "FRS",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-16",
            "fournisseur_id": 6,
            "id": 53,
            "magasin_id": "FRI",
            "nom": "FROM EMMENTAL RAPE KG",
            "nom_court": "FROM EMM/E KG",
            "obsolete": 0,
            "ordi": "Matth2-PC",
            "prix_actuel": 7.7015,
            "prix_moyen": 7.7194,
            "qte_mini": 5,
            "qte_stock": 4,
            "rations": 15,
            "rayon_id": "FRS",
            "saisie": "2022-09-16",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 5,
            "id": 54,
            "magasin_id": "FRI",
            "nom": "FROM ST MARCELLIN",
            "nom_court": "FROM ST /LLIN",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 1.2385,
            "prix_moyen": 1.2385,
            "qte_mini": 0,
            "qte_stock": 0,
            "rations": 0,
            "rayon_id": "FRS",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-08-21",
            "fournisseur_id": 1,
            "id": 55,
            "magasin_id": "RES",
            "nom": "GAUFFRES PQT X 5",
            "nom_court": "GAUFFRES/ X 5",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 1.99,
            "prix_moyen": 1.99,
            "qte_mini": 5,
            "qte_stock": 0,
            "rations": 50,
            "rayon_id": "SCR",
            "saisie": "2022-08-21",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 5,
            "id": 56,
            "magasin_id": "RES",
            "nom": "HUILE COLZA",
            "nom_court": "HUILE CO/OLZA",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 2.751,
            "prix_moyen": 2.751,
            "qte_mini": 0,
            "qte_stock": 0,
            "rations": 0,
            "rayon_id": "CND",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        },
        {
            "colis_par": 1,
            "dernier_achat": "2022-09-19",
            "fournisseur_id": 6,
            "id": 57,
            "magasin_id": "RES",
            "nom": "HUILE OLIVE 1L",
            "nom_court": "HUILE OL/E 1L",
            "obsolete": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "prix_actuel": 7.049,
            "prix_moyen": 7.049,
            "qte_mini": 15,
            "qte_stock": 3,
            "rations": 0,
            "rayon_id": "CND",
            "saisie": "2022-09-19",
            "tx_tva": 5.5,
            "unite_colis": "pqt",
            "unite_stock": "kg"
        }
    ]
StMouvement_data =  [
        {
            "analytique_id": "00",
            "article_id": 38,
            "fournisseur_id": 1,
            "id": 1,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 1,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 0.1866,
            "qtemouvement": -72,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 31,
            "fournisseur_id": 1,
            "id": 2,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 1,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 0.0904,
            "qtemouvement": -50,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 54,
            "fournisseur_id": 1,
            "id": 3,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 1.2385,
            "qtemouvement": -18,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 3,
            "fournisseur_id": 1,
            "id": 4,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 1,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 0.49,
            "qtemouvement": -17,
            "saisie": "2024-12-05",
            "sens": -1,
            "service": 1,
            "transfert": "2024-12-04"
        },
        {
            "analytique_id": "00",
            "article_id": 20,
            "fournisseur_id": 1,
            "id": 5,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 10,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 1.29,
            "qtemouvement": -12,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 42,
            "fournisseur_id": 1,
            "id": 6,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 0.15,
            "qtemouvement": -10,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 49,
            "fournisseur_id": 1,
            "id": 7,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 8.698,
            "qtemouvement": -10,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 5,
            "fournisseur_id": 1,
            "id": 8,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 10,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 0.7764,
            "qtemouvement": -9,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 6,
            "fournisseur_id": 1,
            "id": 9,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 6.0483,
            "qtemouvement": -8,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 2,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 25,
            "fournisseur_id": 1,
            "id": 10,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 5,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 1.99,
            "qtemouvement": -7,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 2,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 19,
            "fournisseur_id": 1,
            "id": 11,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 16,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 1.1151,
            "qtemouvement": -5,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 2,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 15,
            "fournisseur_id": 1,
            "id": 12,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 13,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 1.3757,
            "qtemouvement": -5,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 2,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 2,
            "fournisseur_id": 1,
            "id": 13,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 8,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 1.7097,
            "qtemouvement": -5,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 51,
            "fournisseur_id": 1,
            "id": 14,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 4,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 2.1545,
            "qtemouvement": -5,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 3,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 50,
            "fournisseur_id": 1,
            "id": 15,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 10,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 6.2245,
            "qtemouvement": -5,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 3,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 29,
            "fournisseur_id": 1,
            "id": 16,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 5,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 1.89,
            "qtemouvement": -3,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 3,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 8,
            "fournisseur_id": 1,
            "id": 17,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 10,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 2.47,
            "qtemouvement": -3,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 3,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 13,
            "fournisseur_id": 1,
            "id": 18,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 5,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 2.59,
            "qtemouvement": -3,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 4,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 9,
            "fournisseur_id": 1,
            "id": 19,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 5,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 2.99,
            "qtemouvement": -3,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 46,
            "fournisseur_id": 1,
            "id": 20,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 3.1966,
            "qtemouvement": -3,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 0,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 47,
            "fournisseur_id": 1,
            "id": 21,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 8,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 3.3021,
            "qtemouvement": -3,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 7,
            "fournisseur_id": 1,
            "id": 22,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 30,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 5.7761,
            "qtemouvement": -3,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 12,
            "fournisseur_id": 1,
            "id": 23,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 1.7175,
            "qtemouvement": -2,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 55,
            "fournisseur_id": 1,
            "id": 24,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 50,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 1.99,
            "qtemouvement": -2,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 40,
            "fournisseur_id": 1,
            "id": 25,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 20,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 2.2055,
            "qtemouvement": -2,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 36,
            "fournisseur_id": 1,
            "id": 26,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 10,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "od-out",
            "prixunit": 2.32,
            "qtemouvement": -2,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "40",
            "article_id": 32,
            "fournisseur_id": 1,
            "id": 27,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 20,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "camp",
            "prixunit": 2.9685,
            "qtemouvement": -2,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 17,
            "fournisseur_id": 1,
            "id": 28,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 5,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 4.0375,
            "qtemouvement": -2,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 44,
            "fournisseur_id": 1,
            "id": 29,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 4.1181,
            "qtemouvement": -2,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 26,
            "fournisseur_id": 1,
            "id": 30,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 50,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 5.5566,
            "qtemouvement": -2,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 53,
            "fournisseur_id": 1,
            "id": 31,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 15,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 7.7373,
            "qtemouvement": -2,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 37,
            "fournisseur_id": 1,
            "id": 32,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 1,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 0.3,
            "qtemouvement": -1,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 33,
            "fournisseur_id": 1,
            "id": 33,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 1.4075,
            "qtemouvement": -1,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 24,
            "fournisseur_id": 1,
            "id": 34,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 100,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "repas",
            "prixunit": 4.76,
            "qtemouvement": -1,
            "saisie": "2022-09-24",
            "sens": -1,
            "service": 5,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 4,
            "fournisseur_id": 4,
            "id": 35,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 12,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 4.18,
            "qtemouvement": 2,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 11,
            "fournisseur_id": 4,
            "id": 36,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 1.29,
            "qtemouvement": 3,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 29,
            "fournisseur_id": 4,
            "id": 37,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 5,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 1.89,
            "qtemouvement": 5,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 13,
            "fournisseur_id": 4,
            "id": 38,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 5,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 2.59,
            "qtemouvement": 5,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 9,
            "fournisseur_id": 4,
            "id": 39,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 5,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 2.99,
            "qtemouvement": 5,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 17,
            "fournisseur_id": 4,
            "id": 40,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 5,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 3.99,
            "qtemouvement": 5,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 25,
            "fournisseur_id": 4,
            "id": 41,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 5,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 1.99,
            "qtemouvement": 10,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 20,
            "fournisseur_id": 4,
            "id": 42,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 10,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 1.29,
            "qtemouvement": 12,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 3,
            "fournisseur_id": 4,
            "id": 43,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 1,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 0.49,
            "qtemouvement": 20,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 35,
            "fournisseur_id": 5,
            "id": 44,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 16.421,
            "qtemouvement": 1,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 22,
            "fournisseur_id": 5,
            "id": 45,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 10,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 3.4751,
            "qtemouvement": 2,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 23,
            "fournisseur_id": 5,
            "id": 46,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 10,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 8.3482,
            "qtemouvement": 2,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 52,
            "fournisseur_id": 5,
            "id": 47,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 8,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 11.9373,
            "qtemouvement": 2,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 28,
            "fournisseur_id": 5,
            "id": 48,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 25,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 6.908,
            "qtemouvement": 3,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 41,
            "fournisseur_id": 5,
            "id": 49,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 15,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 7.3037,
            "qtemouvement": 3,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 39,
            "fournisseur_id": 5,
            "id": 50,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 840,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 7.671,
            "qtemouvement": 3,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 32,
            "fournisseur_id": 5,
            "id": 51,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 20,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 3.9325,
            "qtemouvement": 4,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 14,
            "fournisseur_id": 5,
            "id": 52,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 15,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 1.304,
            "qtemouvement": 5,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 51,
            "fournisseur_id": 5,
            "id": 53,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 4,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 2.3674,
            "qtemouvement": 5,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 45,
            "fournisseur_id": 5,
            "id": 54,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 7,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 4.4521,
            "qtemouvement": 5,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 50,
            "fournisseur_id": 5,
            "id": 55,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 10,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 7.1107,
            "qtemouvement": 5,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 56,
            "fournisseur_id": 5,
            "id": 56,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 2.751,
            "qtemouvement": 6,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 1,
            "fournisseur_id": 5,
            "id": 57,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 20,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 4.588,
            "qtemouvement": 6,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 10,
            "fournisseur_id": 5,
            "id": 58,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 1.2396,
            "qtemouvement": 10,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 27,
            "fournisseur_id": 5,
            "id": 59,
            "jour": "2022-09-17",
            "nbcolis": 1,
            "nbrations": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 8.48,
            "qtemouvement": 10,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 18,
            "fournisseur_id": 5,
            "id": 60,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 7,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 12.2696,
            "qtemouvement": 10,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 16,
            "fournisseur_id": 5,
            "id": 61,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 14.5906,
            "qtemouvement": 10,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 57,
            "fournisseur_id": 5,
            "id": 62,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 7.049,
            "qtemouvement": 12,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 54,
            "fournisseur_id": 5,
            "id": 63,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 0,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 1.2385,
            "qtemouvement": 18,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 21,
            "fournisseur_id": 5,
            "id": 64,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 1,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 0.7242,
            "qtemouvement": 80,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 48,
            "fournisseur_id": 5,
            "id": 65,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 1,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 0.2278,
            "qtemouvement": 110,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 30,
            "fournisseur_id": 5,
            "id": 66,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 1,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 0.844,
            "qtemouvement": 144,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 34,
            "fournisseur_id": 5,
            "id": 67,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 1,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 0.196,
            "qtemouvement": 180,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 31,
            "fournisseur_id": 5,
            "id": 68,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 1,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 0.0956,
            "qtemouvement": 200,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        },
        {
            "analytique_id": "00",
            "article_id": 43,
            "fournisseur_id": 5,
            "id": 69,
            "jour": "2022-09-19",
            "nbcolis": 1,
            "nbrations": 1,
            "ordi": "DESKTOP-VKOLCTJ",
            "origine": "achat",
            "prixunit": 0.0679,
            "qtemouvement": 360,
            "saisie": "2022-09-24",
            "sens": 1,
            "service": 1,
            "transfert": None
        }
    ]
StInventaire_data = [
        {
            "article_id": 27,
            "article_nom": "AIGUI POULET GEL",
            "id": 1,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 67.84,
            "ordi": "JB access",
            "prix_actuel": 8.48,
            "prix_moyen": 8.48,
            "qte_stock": 8,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 28,
            "article_nom": "ANANAS MORC BTE 3/1",
            "id": 2,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 42.59,
            "ordi": "JB access",
            "prix_actuel": 6.908,
            "prix_moyen": 7.0979,
            "qte_stock": 6,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 29,
            "article_nom": "BANANES KG",
            "id": 3,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 1.89,
            "prix_moyen": 1.89,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 30,
            "article_nom": "BARRES GLACEE UNITE",
            "id": 4,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 119.85,
            "ordi": "JB access",
            "prix_actuel": 0.844,
            "prix_moyen": 0.844,
            "qte_stock": 142,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 31,
            "article_nom": "BEURRE MICRO X 100",
            "id": 5,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 44.71,
            "ordi": "JB access",
            "prix_actuel": 0.0956,
            "prix_moyen": 0.0894,
            "qte_stock": 500,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 32,
            "article_nom": "BEURRE PLQ 250G PIEC",
            "id": 6,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 11.8,
            "ordi": "JB access",
            "prix_actuel": 3.9325,
            "prix_moyen": 3.9325,
            "qte_stock": 3,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 33,
            "article_nom": "BISCUIT BN PAQ DE 15",
            "id": 7,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 2.3,
            "prix_moyen": 2.3,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 34,
            "article_nom": "BISCUITS PORTIONS",
            "id": 8,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 59.64,
            "ordi": "JB access",
            "prix_actuel": 0.196,
            "prix_moyen": 0.1923,
            "qte_stock": 310,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 35,
            "article_nom": "BOUIL VEAU LIE",
            "id": 9,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 16.421,
            "prix_moyen": 16.421,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 36,
            "article_nom": "BRIOCHE TRANCHEE",
            "id": 10,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 9.28,
            "ordi": "JB access",
            "prix_actuel": 2.32,
            "prix_moyen": 2.32,
            "qte_stock": 4,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 37,
            "article_nom": "BRIOCHETTES 130g",
            "id": 11,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 1.92,
            "ordi": "JB access",
            "prix_actuel": 0.16,
            "prix_moyen": 0.16,
            "qte_stock": 12,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 38,
            "article_nom": "BROWNIES INDIVIDUEL",
            "id": 12,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 0.1866,
            "prix_moyen": 0.1866,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 39,
            "article_nom": "CAFE ARABICA KG",
            "id": 13,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 7.67,
            "ordi": "JB access",
            "prix_actuel": 7.671,
            "prix_moyen": 7.671,
            "qte_stock": 1,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 40,
            "article_nom": "CEREALES DU MATIN",
            "id": 14,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 6.5,
            "ordi": "JB access",
            "prix_actuel": 2.09,
            "prix_moyen": 2.167,
            "qte_stock": 3,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 41,
            "article_nom": "CHANTILLY BOMBE 1L",
            "id": 15,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 72.18,
            "ordi": "JB access",
            "prix_actuel": 7.3037,
            "prix_moyen": 7.2182,
            "qte_stock": 10,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 42,
            "article_nom": "CHOCOLAT POUDRE DOSETTES",
            "id": 16,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 15,
            "ordi": "JB access",
            "prix_actuel": 0.15,
            "prix_moyen": 0.15,
            "qte_stock": 100,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 43,
            "article_nom": "CONFITURE INDIV BARQ UNITE",
            "id": 17,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 0.0679,
            "prix_moyen": 0.0679,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 44,
            "article_nom": "CONFITURE POT 320G UNIT",
            "id": 18,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 34.3,
            "ordi": "JB access",
            "prix_actuel": 4.9,
            "prix_moyen": 4.9,
            "qte_stock": 7,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 45,
            "article_nom": "COTES DE PORC GEL KG",
            "id": 19,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 4.4521,
            "prix_moyen": 4.4521,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 46,
            "article_nom": "CREME ANGLAISE",
            "id": 20,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 3.1966,
            "prix_moyen": 3.1966,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 47,
            "article_nom": "CREME FR LIQU L/C 1L",
            "id": 21,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 22.41,
            "ordi": "JB access",
            "prix_actuel": 3.1544,
            "prix_moyen": 3.2008,
            "qte_stock": 7,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 48,
            "article_nom": "CROISSANTS GEL UNITE",
            "id": 22,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 3.42,
            "ordi": "JB access",
            "prix_actuel": 0.2278,
            "prix_moyen": 0.2278,
            "qte_stock": 15,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 49,
            "article_nom": "CUB COLIN ALK CEREAL",
            "id": 23,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 8.6615,
            "prix_moyen": 8.6615,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 50,
            "article_nom": "FROM BRESSE BLEU 500GRS",
            "id": 24,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 7.1107,
            "prix_moyen": 7.1107,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 51,
            "article_nom": "FROM CAMEMBERT 250GRS",
            "id": 25,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 2.3674,
            "prix_moyen": 2.3674,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 52,
            "article_nom": "FROM COMTE BLOC X 500 GRS",
            "id": 26,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 11.9373,
            "prix_moyen": 11.9373,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 53,
            "article_nom": "FROM EMMENTAL RAPE KG",
            "id": 27,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 30.88,
            "ordi": "JB access",
            "prix_actuel": 7.7015,
            "prix_moyen": 7.7194,
            "qte_stock": 4,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 54,
            "article_nom": "FROM ST MARCELLIN",
            "id": 28,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 1.2385,
            "prix_moyen": 1.2385,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 55,
            "article_nom": "GAUFFRES PQT X 5",
            "id": 29,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 1.99,
            "prix_moyen": 1.99,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 56,
            "article_nom": "HUILE COLZA",
            "id": 30,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 2.751,
            "prix_moyen": 2.751,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 57,
            "article_nom": "HUILE OLIVE 1L",
            "id": 31,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 21.15,
            "ordi": "JB access",
            "prix_actuel": 7.049,
            "prix_moyen": 7.049,
            "qte_stock": 3,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 1,
            "article_nom": "HUILE TOURNESOL  X 1L",
            "id": 32,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 45.19,
            "ordi": "JB access",
            "prix_actuel": 4.588,
            "prix_moyen": 4.1078,
            "qte_stock": 11,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 2,
            "article_nom": "JUS ORANGE/POMME PtDej",
            "id": 33,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 221.26,
            "ordi": "JB access",
            "prix_actuel": 1.18,
            "prix_moyen": 1.702,
            "qte_stock": 130,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 3,
            "article_nom": "KIWIS FRAIS PIECE",
            "id": 34,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 0.49,
            "prix_moyen": 0.49,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 4,
            "article_nom": "LAIT COCO BTE 1L",
            "id": 35,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 4.19,
            "prix_moyen": 4.19,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 5,
            "article_nom": "LAIT UHT 1L",
            "id": 36,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 4.4099,
            "prix_moyen": 4.4099,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 6,
            "article_nom": "LARDONS FUMES     KG",
            "id": 37,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 60.48,
            "ordi": "JB access",
            "prix_actuel": 6.0483,
            "prix_moyen": 6.0483,
            "qte_stock": 10,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 7,
            "article_nom": "MAIS DOUX        3/1",
            "id": 38,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 109.75,
            "ordi": "JB access",
            "prix_actuel": 5.7761,
            "prix_moyen": 5.7761,
            "qte_stock": 19,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 8,
            "article_nom": "MUESLI CROUST",
            "id": 39,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 2.47,
            "prix_moyen": 2.47,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 9,
            "article_nom": "NECTARINES KG",
            "id": 40,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 2.99,
            "prix_moyen": 2.99,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 10,
            "article_nom": "OIGNON EMINCE GEL KG",
            "id": 41,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 1.2396,
            "prix_moyen": 1.2396,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 11,
            "article_nom": "OIGNONS FRAIS",
            "id": 42,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 1.29,
            "prix_moyen": 1.29,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 12,
            "article_nom": "OLIVES NOIRES 4/4",
            "id": 43,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 1.72,
            "ordi": "JB access",
            "prix_actuel": 1.7175,
            "prix_moyen": 1.7175,
            "qte_stock": 1,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 13,
            "article_nom": "ORANGES FRAICHES  KG",
            "id": 44,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 1.055,
            "prix_moyen": 1.055,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 14,
            "article_nom": "PATES COQUILLETTE KG",
            "id": 45,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 6.52,
            "ordi": "JB access",
            "prix_actuel": 1.304,
            "prix_moyen": 1.304,
            "qte_stock": 5,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 15,
            "article_nom": "PATES FARFALLES KG",
            "id": 46,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 6.88,
            "ordi": "JB access",
            "prix_actuel": 1.3757,
            "prix_moyen": 1.3757,
            "qte_stock": 5,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 16,
            "article_nom": "PAUPIETTE VEAU GEL",
            "id": 47,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 29.18,
            "ordi": "JB access",
            "prix_actuel": 14.5906,
            "prix_moyen": 14.5906,
            "qte_stock": 2,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 17,
            "article_nom": "RAISIN FRAIS KG",
            "id": 48,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 8.97,
            "ordi": "JB access",
            "prix_actuel": 2.99,
            "prix_moyen": 2.99,
            "qte_stock": 3,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 18,
            "article_nom": "RAVIOLIS FROMAGE SURG",
            "id": 49,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 12.2696,
            "prix_moyen": 12.2696,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 19,
            "article_nom": "RIZ LONG GR US KG",
            "id": 50,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 8.92,
            "ordi": "JB access",
            "prix_actuel": 1.1151,
            "prix_moyen": 1.1151,
            "qte_stock": 8,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 20,
            "article_nom": "SALADES DIVERSES",
            "id": 51,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 1.3609,
            "prix_moyen": 1.3609,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 21,
            "article_nom": "SUNDAE BTE CONG",
            "id": 52,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 37.66,
            "ordi": "JB access",
            "prix_actuel": 0.7242,
            "prix_moyen": 0.7242,
            "qte_stock": 52,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 22,
            "article_nom": "TARTES CITRON POUR 10",
            "id": 53,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 32.31,
            "ordi": "JB access",
            "prix_actuel": 3.4751,
            "prix_moyen": 5.385,
            "qte_stock": 6,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 23,
            "article_nom": "TARTES MYRTILLES POUR 10",
            "id": 54,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 33.39,
            "ordi": "JB access",
            "prix_actuel": 8.3482,
            "prix_moyen": 8.3482,
            "qte_stock": 4,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 24,
            "article_nom": "THE DIVERS 100SCH",
            "id": 55,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 4.76,
            "ordi": "JB access",
            "prix_actuel": 4.76,
            "prix_moyen": 4.76,
            "qte_stock": 1,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 25,
            "article_nom": "TOMATES FRAICHES",
            "id": 56,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 0,
            "ordi": "JB access",
            "prix_actuel": 2.39,
            "prix_moyen": 2.39,
            "qte_stock": 0,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        },
        {
            "article_id": 26,
            "article_nom": "TOMATES PEL/CONC 5/1",
            "id": 57,
            "jour": "2022-09-30",
            "modifiable": 0,
            "montant": 5.56,
            "ordi": "JB access",
            "prix_actuel": 5.5566,
            "prix_moyen": 5.5566,
            "qte_stock": 1,
            "saisie": "2023-02-09",
            "unite_stock": "kg"
        }
    ]

LstTablesData = [GeAnalytique_data,StMagasin_data,StRayon_data,StFournisseur_data,
                 StEffectif_data,StArticle_data,StMouvement_data,StInventaire_data
                 ]
LstTablesNom = [GeAnalytique, StMagasin, StRayon, StFournisseur, StEffectif,
                StArticle, StMouvement, StInventaire
                ]

ADMIN_ID = 'admin'
USER_ID = 'user'
PASSWORD = 'MPdemo-43'



class Command(BaseCommand):

    help = 'Initialize project for local development'

    def handle(self, *args, **options):
        self.stdout.write(self.style.MIGRATE_HEADING(self.help))

        for table in LstTablesNom:
            table.objects.all().delete()
            table_data = LstTablesData[LstTablesNom.index(table)]

            for item in table_data:
                table.objects.create(**item)
        UserModel.objects.create_superuser(ADMIN_ID, 'admin@foo.fr', PASSWORD)
        UserModel.objects.create_user(USER_ID, 'user@foo.fr', PASSWORD)

        self.stdout.write(self.style.SUCCESS("All Done !"))
