# Generated by Django 4.1.5 on 2023-01-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noegestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytiques',
            fields=[
                ('code_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('abrege', models.CharField(max_length=32)),
                ('params', models.TextField(blank=True, default='')),
                ('axe', models.CharField(blank=True, default='', max_length=32)),
                ('saisie', models.DateField(auto_now=True, null=True)),
                ('obsolete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Codes Analytiques de gestion',
                'db_table': 'ge_analytiques',
                'ordering': ['code_id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.BigAutoField(default=1, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(db_index=True, max_length=128, unique=True)),
                ('nom_court', models.CharField(db_index=True, max_length=32, unique=True)),
                ('unite_stock', models.CharField(help_text='Unité de base pour compter, accompagne le nom', max_length=8)),
                ('unite_colis', models.CharField(help_text='Utilisé lors des entrées pour un prix au conditionnement', max_length=8)),
                ('colis_par', models.DecimalField(decimal_places=4, default=1, help_text="Nbre d'unités stock par unité de colis", max_digits=10)),
                ('magasin', models.CharField(choices=[('FRI', 'Frigo'), ('SUR', 'Congel'), ('RES', 'Reserve')], db_index=True, max_length=32)),
                ('rayon', models.CharField(choices=[('BSS', 'Boissons'), ('CND', 'Condiments'), ('FCL', 'Féculents'), ('FRS', 'Frais'), ('FRT', 'Fruits'), ('LGM', 'Légumes'), ('PSS', 'Poisson'), ('SCR', 'Sucré'), ('VND', 'Viande')], db_index=True, max_length=32)),
                ('rations', models.DecimalField(decimal_places=4, default=1, help_text='Nbre de rations par unité de stock', max_digits=10)),
                ('fournisseur', models.CharField(blank=True, db_index=True, default='', help_text='Proposé par défaut', max_length=32)),
                ('qte_stock', models.DecimalField(db_index=True, decimal_places=4, default=0, help_text='recalculé régulièrement pour inventaire', max_digits=10)),
                ('tx_tva', models.DecimalField(decimal_places=4, default=5.5, help_text='tx de TVA en %', max_digits=10)),
                ('qte_mini', models.IntegerField(blank=True, help_text="Déclencheur d'alerte pour réappro", null=True)),
                ('qte_saison', models.IntegerField(blank=True, help_text='Seuil souhaitable en haute saison', null=True)),
                ('prix_moyen', models.DecimalField(blank=True, decimal_places=4, help_text='Prix unitaire moyen historique du stock', max_digits=10, null=True)),
                ('prix_actuel', models.DecimalField(blank=True, decimal_places=4, help_text='Dernier prix TTC unitaire livré ou de réappro', max_digits=10, null=True)),
                ('dernier_achat', models.DateField(help_text='Date de dernière entrée avec prix saisi', null=True)),
                ('ordi', models.CharField(blank=True, help_text="Nom de l'ordi utilisé pour l'entrée ou la modif", max_length=32)),
                ('saisie', models.DateField(help_text="Date de l'entrée ou la modif de l'item", null=True)),
            ],
            options={
                'db_table': 'st_articles',
            },
        ),
        migrations.CreateModel(
            name='Mouvements',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jour', models.DateField()),
                ('origine', models.CharField(db_index=True, max_length=8)),
                ('fournisseur', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('nbcolis', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('qtemouvement', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prixunit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('service', models.IntegerField(default=3, help_text='Service repas concerné')),
                ('nbrations', models.DecimalField(decimal_places=4, default=0, help_text='Nbre de ration par qteMouvement', max_digits=8)),
                ('transfert', models.DateField(help_text='non modifiable si date de transfert', null=True)),
                ('ordi', models.CharField(blank=True, default='', help_text='pour tracer les mouvements', max_length=32)),
                ('datesaisie', models.DateField(null=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='noegestion.articles')),
                ('code_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='noegestion.analytiques')),
            ],
            options={
                'db_table': 'st_mouvements',
                'index_together': {('jour', 'code_id', 'origine')},
            },
        ),
        migrations.CreateModel(
            name='Inventaires',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jour', models.DateField()),
                ('libelle', models.CharField(db_index=True, help_text=' Conserve le nom historique', max_length=128)),
                ('unite_stock', models.CharField(help_text='Unité de base pour compter, accompagne le nom', max_length=8)),
                ('qte_stock', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('prix_moyen', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('prix_actuel', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('modifiable', models.BooleanField(null=True)),
                ('ordi', models.CharField(max_length=32, null=True)),
                ('saisie', models.DateField(null=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='noegestion.articles')),
            ],
            options={
                'db_table': 'st_inventaires',
                'unique_together': {('jour', 'article_id')},
            },
        ),
        migrations.CreateModel(
            name='Effectifs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jour', models.DateField()),
                ('midi_clients', models.IntegerField()),
                ('midi_repas', models.IntegerField()),
                ('soir_clients', models.IntegerField()),
                ('soir_repas', models.IntegerField()),
                ('prevu_clients', models.IntegerField()),
                ('prevu_repas', models.IntegerField()),
                ('ordi', models.CharField(max_length=32)),
                ('saisie', models.DateField(null=True)),
                ('code_id', models.ForeignKey(default='00', on_delete=django.db.models.deletion.DO_NOTHING, to='noegestion.analytiques')),
            ],
            options={
                'db_table': 'st_effectifs',
                'unique_together': {('jour', 'code_id')},
            },
        ),
    ]
