# Generated by Django 4.1.5 on 2023-02-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noegestion', '0002_analytiques_articles_mouvements_inventaires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytiques',
            name='obsolete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='analytiques',
            name='params',
            field=models.TextField(default='', null=True),
        ),
    ]
