# Generated by Django 4.1.5 on 2023-02-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noegestion', '0003_alter_analytiques_obsolete_alter_analytiques_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='nom_court',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='mouvements',
            name='fournisseur',
            field=models.CharField(db_index=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements',
            name='nbrations',
            field=models.DecimalField(decimal_places=4, help_text='Nbre de ration par qteMouvement', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='mouvements',
            name='service',
            field=models.IntegerField(default=3, help_text='Service repas concerné', null=True),
        ),
    ]
