# Generated by Django 4.2 on 2023-05-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noegestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geanalytique',
            old_name='label',
            new_name='nom',
        ),
    ]
