# Generated by Django 4.2 on 2023-05-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noegestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stmouvement',
            name='test',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
