# Generated by Django 4.2 on 2023-05-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noegestion', '0002_stmouvement_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stmouvement',
            name='test',
        ),
    ]
